functional:
  - Пользователь должен иметь возможность искать товары по ключевому слову или категории
  - Пользователь должен иметь возможность фильтровать товары
  - Пользователь должен иметь возможность просматривать товары и просматривать подробную информацию о товаре
  - Пользователь должен иметь возможность добавлять товары в корзину и просматривать содержимое корзины 
non-functional:
  - Сайт нужно разработать с учетом удобства использования и оптимизировать для скорости работы
  - Сайт должен быть безопасным и защищать данные пользователя
  - Сайт должен иметь мобильную версию
  - Сайт нужно протестировать на совместимость с последними версиями браузеров
  - Важно, чтобы сайт мог обрабатывать большое количество трафика
implicit:
  - Пользователь должен иметь возможность фильтровать характеристики товара(цвет, размер и тому подобные параметры)
  - На странице списки товаров должа быть кнопка для прокручивания страницы в начало списка
  - Сайт должен иметь возможность подстраиватся под браузер пользователя. Например: Оформление интерфейса темного цвета и т.п
  - Пользователь должен иметь возможность связаться с поддержкой в сплывающем чате или позвонить по номеру указанным на сайте
  - Пользователь должен иметь возможность сортировать товары(По цене, популярности и рейтингу)
